UPDATE Role SET jobSpec = 'https://kainossoftwareltd.sharepoint.com/people/Job%20Specifications/Forms/AllItems.aspx?id=%2Fpeople%2FJob%20Specifications%2FEngineering%2FJob%20Profile%20%2D%20Dynamics%20365%20PP%20Solution%20Architect%20%28M%29%2Epdf&parent=%2Fpeople%2FJob%20Specifications%2FEngineering', responsibilities = 'big farming', description = 'do stuff' WHERE id = 1;

UPDATE Role SET closingDate = CURRENT_DATE()+1, jobSpec = 'https://kainossoftwareltd.sharepoint.com/people/Job%20Specifications/Forms/AllItems.aspx?id=%2Fpeople%2FJob%20Specifications%2FEngineering%2FJob%20Profile%20%2D%20Dynamics%20365%20PP%20Solution%20Architect%20%28M%29%2Epdf&parent=%2Fpeople%2FJob%20Specifications%2FEngineering', responsibilities = 'test', description = 'do stuff' WHERE id = 2;

UPDATE Role SET closingDate = CURRENT_DATE()+3, jobSpec = 'https://kainossoftwareltd.sharepoint.com/people/Job%20Specifications/Forms/AllItems.aspx?id=%2Fpeople%2FJob%20Specifications%2FEngineering%2FJob%20Profile%20%2D%20Dynamics%20365%20PP%20Solution%20Architect%20%28M%29%2Epdf&parent=%2Fpeople%2FJob%20Specifications%2FEngineering', responsibilities = 'test 2', description = 'do stuff' WHERE id = 3;

UPDATE Role SET closingDate = CURRENT_DATE()+6, jobSpec = 'https://kainossoftwareltd.sharepoint.com/people/Job%20Specifications/Forms/AllItems.aspx?id=%2Fpeople%2FJob%20Specifications%2FEngineering%2FJob%20profile%20%2D%20Senior%20Software%20Engieneer%20%28Senior%20Associate%29%2Epdf&parent=%2Fpeople%2FJob%20Specifications%2FEngineering', responsibilities = 'fix bugs', description = 'spend your days fixing bugs' WHERE id = 4;

UPDATE Role SET closingDate = CURRENT_DATE()+16, jobSpec = 'https://kainossoftwareltd.sharepoint.com/people/Job%20Specifications/Forms/AllItems.aspx?id=%2Fpeople%2FJob%20Specifications%2FEngineering%2FJob%20profile%20%2D%20Lead%20Software%20Engineer%20%28Consultant%29%2Epdf&parent=%2Fpeople%2FJob%20Specifications%2FEngineering', responsibilities = 'fix more bugs', description = 'lead people and fix bugs' WHERE id = 5;

UPDATE Role SET closingDate = CURRENT_DATE()+20, jobSpec = 'https://kainossoftwareltd.sharepoint.com/people/Job%20Specifications/Forms/AllItems.aspx?id=%2Fpeople%2FJob%20Specifications%2FEngineering%2FJob%20profile%20%20Test%20Engineer%20%28Associate%29%2Epdf&parent=%2Fpeople%2FJob%20Specifications%2FEngineering', responsibilities = 'BUILD', description = 'BUILD BUILDINGS' WHERE id = 6;

UPDATE Role SET closingDate = CURRENT_DATE()+8, jobSpec = 'https://kainossoftwareltd.sharepoint.com/people/Job%20Specifications/Forms/AllItems.aspx?id=%2Fpeople%2FJob%20Specifications%2FEngineering%2FJob%20profile%20%2D%20Lead%20Test%20Engineer%20%28Consultant%29%2Epdf&parent=%2Fpeople%2FJob%20Specifications%2FEngineering', responsibilities = 'BUILD BIG', description = 'BIGGER, BETTER, FASTER, STRONGER' WHERE id = 7;

UPDATE Role SET closingDate = CURRENT_DATE()+100, jobSpec = 'https://kainossoftwareltd.sharepoint.com/people/Job%20Specifications/Forms/AllItems.aspx?id=%2Fpeople%2FJob%20Specifications%2FEngineering%2FJob%20profile%20%20Test%20Engineer%20%28Associate%29%2Epdf&parent=%2Fpeople%2FJob%20Specifications%2FEngineering', responsibilities = 'big tubes', description = 'he loves tubes' WHERE id = 8;

UPDATE Role SET closingDate = CURRENT_DATE()+20, jobSpec = 'https://kainossoftwareltd.sharepoint.com/people/Job%20Specifications/Forms/AllItems.aspx?id=%2Fpeople%2FJob%20Specifications%2FEngineering%2FJob%20profile%20%2D%20Test%20Manager%20%28Consultant%29%2Epdf&parent=%2Fpeople%2FJob%20Specifications%2FEngineering', responsibilities = 'platforms yes', description = 'teach platforms' WHERE id = 9;