name: JMeter Test

on:
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"  # Runs at midnight UTC daily

jobs:
  run-jmeter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Install JMeter
        run: |
          sudo apt-get update
          sudo apt-get install -y wget
          wget https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-5.4.1.tgz
          tar -xvzf apache-jmeter-5.4.1.tgz
          export JMETER_HOME=$(pwd)/apache-jmeter-5.4.1
          export PATH=$JMETER_HOME/bin:$PATH

      - name: Run JMeter Test
        run: |
          ./apache-jmeter-5.4.1/bin/jmeter -n -t src/test/jmeter/test-plan.jmx -l results.jtl

      - name: Upload JMeter results
        uses: actions/upload-artifact@v2
        with:
          name: jmeter-results
          path: results.jtl